wandb_version: 1

epochs:
  desc: null
  value: 8
data:
  desc: null
  value: data/processed/
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692983295.490455
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.11.0
      5: 0.15.8
      8:
      - 3
      - 5
