wandb_version: 1

epochs:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.001
data:
  desc: null
  value: data/processed/
train_split_size:
  desc: null
  value: 0.8
batch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.8
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692986054.6114
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      - 103
      3:
      - 16
      - 23
      4: 3.11.0
      5: 0.15.8
      8:
      - 3
      - 5
